services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    ports:
      - "3000:3000"
    volumes:
      - ./docuseal:/data/docuseal
      - ./app/controllers:/app/app/controllers
      - ./app/javascript:/app/app/javascript
      - ./app/jobs:/app/app/jobs
      - ./app/mailers:/app/app/mailers
      - ./app/models:/app/app/models
      - ./app/services:/app/app/services
      - ./app/views:/app/app/views
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./lib:/app/lib
      - ./config:/app/config
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./tailwind.application.config.js:/app/tailwind.application.config.js
      - ./tailwind.form.config.js:/app/tailwind.form.config.js
    entrypoint: ["/app/entrypoint.sh"]
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - HOST=0.0.0.0
      - FORCE_SSL=false
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
    networks:
      - docuseal_net

  postgres:
    image: postgres:15
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - docuseal_net

  caddy:
    image: caddy:latest
    command: caddy reverse-proxy --from localhost --to app:3000
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy_data:/data
    environment:
      - HOST=localhost
    depends_on:
      - app
    networks:
      - docuseal_net

networks:
  docuseal_net:
    driver: bridge